# This file was generated by GoReleaser. DO NOT EDIT.
cask "abrsim" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "b923592c1576334a1a7b4effde30eb98d049822f4e655c81aa505204e4e50408"
      url "https://github.com/Allan-Nava/abrsim/releases/download/v#{version}/abrsim_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5c6f9abe90f0713a880e3ad0feab1d3a5526120c99f225ac9e5a48ad6b05264b"
      url "https://github.com/Allan-Nava/abrsim/releases/download/v#{version}/abrsim_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f66314c6dcea2e50d5ccfdcf0f3c831512d6f218884ceb1da5b6f7ca66f61d0e"
      url "https://github.com/Allan-Nava/abrsim/releases/download/v#{version}/abrsim_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d26fd19ea014dc745327bd7a4b74a216be0eb446e9324ccdf81c7c5fd2fe1c84"
      url "https://github.com/Allan-Nava/abrsim/releases/download/v#{version}/abrsim_#{version}_linux_arm64.tar.gz"
    end
  end

  name "abrsim"
  desc "Simulate what an ABR player does with your HLS ladder on a real network, and report what it cost the viewer"
  homepage "https://github.com/Allan-Nava/abrsim"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "abrsim"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/abrsim"]
    end
  end

  # No zap stanza required

end
