# This file was generated by GoReleaser. DO NOT EDIT.
cask "abrsim" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "647fd5d1b7cb7b98a7cff15bb84b0e2ffd663988549dce62eb13736794b78482"
      url "https://github.com/Allan-Nava/abrsim/releases/download/v#{version}/abrsim_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e6ce168e494e22ccec4f95b1d5bd1b13c20e5c84c3464bd2ebcea42da2c51981"
      url "https://github.com/Allan-Nava/abrsim/releases/download/v#{version}/abrsim_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "11713f1242151f8aa15a850a3e3399406c487e652bac05f6423dad968ef7142a"
      url "https://github.com/Allan-Nava/abrsim/releases/download/v#{version}/abrsim_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7b97351c28d2880ab2aab07ebb038d71c7f33f79111298e9bcabed2ade839486"
      url "https://github.com/Allan-Nava/abrsim/releases/download/v#{version}/abrsim_#{version}_linux_arm64.tar.gz"
    end
  end

  name "abrsim"
  desc "Simulate what an ABR player does with your HLS ladder on a real network, and report what it cost the viewer"
  homepage "https://github.com/Allan-Nava/abrsim"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "abrsim"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/abrsim"]
    end
  end

  # No zap stanza required

end
