# This file was generated by GoReleaser. DO NOT EDIT.
cask "abrsim" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "84a7839e2216722518c050d4770aeeda3493c10ec2ea519ebe8ca1957981bb44"
      url "https://github.com/Allan-Nava/abrsim/releases/download/v#{version}/abrsim_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "506af00b8012808111ec66983de240725955aa37f055663ced0678f124d29019"
      url "https://github.com/Allan-Nava/abrsim/releases/download/v#{version}/abrsim_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b34c03ad6d8be482f47c0fcd601421dafd2381f5aa067cf6b4fd47f0f8681834"
      url "https://github.com/Allan-Nava/abrsim/releases/download/v#{version}/abrsim_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "51fd46af4c06b0b213bb85cb0eb246f6eff52f7f76487297ecfb3bcdc2385c79"
      url "https://github.com/Allan-Nava/abrsim/releases/download/v#{version}/abrsim_#{version}_linux_arm64.tar.gz"
    end
  end

  name "abrsim"
  desc "Simulate what an ABR player does with your HLS ladder on a real network, and report what it cost the viewer"
  homepage "https://github.com/Allan-Nava/abrsim"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "abrsim"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/abrsim"]
    end
  end

  # No zap stanza required

end
