# This file was generated by GoReleaser. DO NOT EDIT.
cask "checkfleet" do
  version "1.31.0"

  on_macos do
    on_arm do
      sha256 "098b96f74865fabde0772add5bd0282b9e026652f1de419922b3993f26a5a55b"
      url "https://github.com/Allan-Nava/checkfleet/releases/download/v#{version}/checkfleet_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "df54c3675b3ad0787f05cd229ef9fb3ded72098c1a96148283c82f59fe2e399d"
      url "https://github.com/Allan-Nava/checkfleet/releases/download/v#{version}/checkfleet_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d1c6fb0ba7ab9ff997bbdfa2c5f12414cd6cdd28a3118b558b513dd46eb5b776"
      url "https://github.com/Allan-Nava/checkfleet/releases/download/v#{version}/checkfleet_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9376c92454b1d00660483f78f83431c3ac4386962061c3418c31354c0510fe75"
      url "https://github.com/Allan-Nava/checkfleet/releases/download/v#{version}/checkfleet_#{version}_linux_amd64.tar.gz"
    end
  end

  name "checkfleet"
  desc "A fleet of domain-aware infrastructure checks in one binary"
  homepage "https://github.com/Allan-Nava/checkfleet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "checkfleet"

  postflight do
    if system_command "/usr/bin/xattr", args: ["-h"], print_stderr: false
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/checkfleet"]
    end
  end

  # No zap stanza required
end
