# This file was generated by GoReleaser. DO NOT EDIT.
cask "checkfleet" do
  version "1.24.0"

  on_macos do
    on_intel do
      sha256 "0b12186ab70bea3dbca917479c341d03708317841ab3d68ea55957aaa17239cf"
      url "https://github.com/Allan-Nava/checkfleet/releases/download/v#{version}/checkfleet_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2e4ed5251bb12c8631ea997d0e6d1ef17ee6b064c3f1257021a69bedb2f477f3"
      url "https://github.com/Allan-Nava/checkfleet/releases/download/v#{version}/checkfleet_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "da6e9a55dec92c211db3710bb08093d7c84042b7185839169fb32168d1f124d8"
      url "https://github.com/Allan-Nava/checkfleet/releases/download/v#{version}/checkfleet_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6e0a93a989003b6436b9c82abc92b422e5750512b07b57352e249869a5041b70"
      url "https://github.com/Allan-Nava/checkfleet/releases/download/v#{version}/checkfleet_#{version}_linux_arm64.tar.gz"
    end
  end

  name "checkfleet"
  desc "A fleet of domain-aware infrastructure checks in one binary"
  homepage "https://github.com/Allan-Nava/checkfleet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "checkfleet"

  postflight do
    if system_command "/usr/bin/xattr", args: ["-h"], print_stderr: false
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/checkfleet"]
    end
  end

  # No zap stanza required

end
