# This file was generated by scripts/render-desktop-cask.sh. DO NOT EDIT.
cask "checkfleet-desktop" do
  version "1.5.0"
  sha256 "19ebb463ca57f4dc670d37a11227cd9d40e220778ece89a4edd24f948abbe78f"

  url "https://github.com/Allan-Nava/checkfleet/releases/download/v#{version}/checkfleet-desktop_v#{version}_darwin_universal.zip"
  name "checkfleet Desktop"
  desc "Desktop app to run the checkfleet infrastructure checks"
  homepage "https://github.com/Allan-Nava/checkfleet"

  livecheck do
    skip "Auto-generated on release."
  end

  # Cask macOS-only (artifact app): Homebrew pretende il depends_on nudo, senza
  # vincolo di versione (il bundle dichiara LSMinimumSystemVersion 10.13, più
  # bassa del minimo che Homebrew supporta, e la forma con versione per quelle
  # release è disabilitata).
  depends_on :macos

  app "checkfleet.app"

  # Il bundle non è firmato né notarizzato: senza togliere la quarantine
  # Gatekeeper rifiuta di aprirlo. Stesso trattamento del cask del CLI.
  postflight do
    if system_command "/usr/bin/xattr", args: ["-h"], print_stderr: false
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/checkfleet.app"]
    end
  end

  zap trash: [
    "~/Library/Caches/com.wails.checkfleet",
    "~/Library/Preferences/com.wails.checkfleet.plist",
    "~/Library/Saved Application State/com.wails.checkfleet.savedState",
    "~/Library/WebKit/com.wails.checkfleet",
  ]
end
