# This file was generated by GoReleaser. DO NOT EDIT.
cask "checkfleet" do
  version "0.122.2"

  on_macos do
    on_intel do
      sha256 "48c3de424c6973673b703b83738e12a2e6bdf54eb161d116c3b9aa3a15d28df4"
      url "https://github.com/Allan-Nava/checkfleet/releases/download/v#{version}/checkfleet_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "665c4b4cb26e6b0c2c437b9e730da5f2bedee21c05788bc46d6e2dc3694a2be1"
      url "https://github.com/Allan-Nava/checkfleet/releases/download/v#{version}/checkfleet_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7fffb4938ee87835809048eac6c858943aa35e3871c697a1c026972a298770f1"
      url "https://github.com/Allan-Nava/checkfleet/releases/download/v#{version}/checkfleet_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d6911597ca0885cd79b4dd74bed0a05ef9edf800068019521fa5fd69e4d7ec3"
      url "https://github.com/Allan-Nava/checkfleet/releases/download/v#{version}/checkfleet_#{version}_linux_arm64.tar.gz"
    end
  end

  name "checkfleet"
  desc "A fleet of domain-aware infrastructure checks in one binary"
  homepage "https://github.com/Allan-Nava/checkfleet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "checkfleet"

  postflight do
    if system_command "/usr/bin/xattr", args: ["-h"], print_stderr: false
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/checkfleet"]
    end
  end

  # No zap stanza required

end
