# This file was generated by GoReleaser. DO NOT EDIT.
cask "galera-doctor" do
  version "0.11.0"

  on_macos do
    on_arm do
      sha256 "193a578c37733c3764819585f8ba7392627e65828b8143a7ea91358f2f70ddc3"
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v#{version}/galera-doctor_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "aa85a1faa977607413162d66a8944cf71ca23d5fb5e7eb32cf9430ba775b9e54"
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v#{version}/galera-doctor_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "22956ced5eac3d15fc14e2d1ca4ba23272e44ead02101b7addc0db75dc76e713"
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v#{version}/galera-doctor_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5c5c19511101ab01644ba5e90ff45a6df987f8c41a1c5867c12fd05874c78d61"
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v#{version}/galera-doctor_#{version}_linux_amd64.tar.gz"
    end
  end

  name "galera-doctor"
  desc "Read-only audit of a Galera cluster: the states its own metrics cannot show"
  homepage "https://github.com/Allan-Nava/galera-doctor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "galera-doctor"

  postflight do
    if system_command "/usr/bin/xattr", args: ["-h"], print_stderr: false
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/galera-doctor"]
    end
  end

  # No zap stanza required
end
