# This file was generated by GoReleaser. DO NOT EDIT.
cask "galera-doctor" do
  version "1.2.0"

  on_macos do
    on_arm do
      sha256 "4ed0158eb27f101a76ec9386b25167444c472a26013221848403dd77e3426378"
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v#{version}/galera-doctor_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0b49db458ca0779a16e4adae13bdccdd7b7385eecdfcd31dd5d6afe1dc0be99f"
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v#{version}/galera-doctor_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7e106b0309ee4c733e084cf523a20e5cb4d978bff81e756d84504af288b64d38"
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v#{version}/galera-doctor_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1add3919a023609dd07f3cc8a88e8a675f0706d0caf00503074899851901ff86"
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v#{version}/galera-doctor_#{version}_linux_amd64.tar.gz"
    end
  end

  name "galera-doctor"
  desc "Read-only audit of a Galera cluster: the states its own metrics cannot show"
  homepage "https://github.com/Allan-Nava/galera-doctor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "galera-doctor"

  postflight do
    if system_command "/usr/bin/xattr", args: ["-h"], print_stderr: false
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/galera-doctor"]
    end
  end

  # No zap stanza required
end
