# This file was generated by GoReleaser. DO NOT EDIT.
cask "galera-doctor" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "0160dc1fda39b0482607a55ce6f33a1a66014555c7188358a886b90f4a6e8c71"
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v#{version}/galera-doctor_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "851dd2a287f6dc047958d6f465235531ba7f52f13c4a4d1e2e7253ebadfb370e"
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v#{version}/galera-doctor_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "474786635b44b4fe8fbc0cde0dfdc79ce268572a29eb5f98fe0aceb71d265c00"
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v#{version}/galera-doctor_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fe1834ed9e96366a5c47ab19186190205d0022b9a5dc51e16a76c0f7c2036c6e"
      url "https://github.com/Allan-Nava/galera-doctor/releases/download/v#{version}/galera-doctor_#{version}_linux_amd64.tar.gz"
    end
  end

  name "galera-doctor"
  desc "Read-only audit of a Galera cluster: the states its own metrics cannot show"
  homepage "https://github.com/Allan-Nava/galera-doctor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "galera-doctor"

  postflight do
    if system_command "/usr/bin/xattr", args: ["-h"], print_stderr: false
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/galera-doctor"]
    end
  end

  # No zap stanza required
end
