# This file was generated by GoReleaser. DO NOT EDIT.
cask "pqprobe" do
  version "0.45.0"

  on_macos do
    on_arm do
      sha256 "e291ec29f547ae0d2b6a077df8b3963fbcf1f678e4e60b3fa2028790e6aafe86"
      url "https://github.com/Allan-Nava/pqprobe/releases/download/v#{version}/pqprobe_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8c50afa90bc41b49109c91c3851820ab9b9db57d574d83d99b114c26a1757d26"
      url "https://github.com/Allan-Nava/pqprobe/releases/download/v#{version}/pqprobe_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b8b15bbd16610c4421cb73ea7c36d2906073798deaf7df0f2faa6fa877fea28d"
      url "https://github.com/Allan-Nava/pqprobe/releases/download/v#{version}/pqprobe_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ce431f16a0cf68a2c45d9902659d15a215d616ed24e730fde95e34ce659257f4"
      url "https://github.com/Allan-Nava/pqprobe/releases/download/v#{version}/pqprobe_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pqprobe"
  desc "Which classes of TLS client can still handshake with this endpoint"
  homepage "https://allan-nava.github.io/pqprobe/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pqprobe"

  postflight do
    if system_command "/usr/bin/xattr", args: ["-h"], print_stderr: false
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pqprobe"]
    end
  end

  # No zap stanza required
end
