# This file was generated by GoReleaser. DO NOT EDIT.
cask "pqprobe" do
  version "0.31.0"

  on_macos do
    on_arm do
      sha256 "df54d97ddf063438f879e823b765f3b1f08b6f69aa8f6b3d7dc68fd3eb9cceed"
      url "https://github.com/Allan-Nava/pqprobe/releases/download/v#{version}/pqprobe_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1105d1e7ee522af09bca49692236795d88c59ec88fe7df568df91877d419c924"
      url "https://github.com/Allan-Nava/pqprobe/releases/download/v#{version}/pqprobe_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "19d7a7d971fca24ecbd5f9e2e52dabf39feb5d9c196ebad927d089b82a351038"
      url "https://github.com/Allan-Nava/pqprobe/releases/download/v#{version}/pqprobe_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "75d0f0a7613e4a2f23330383a671cbac183f42babbcf7d6e9f45dced12486eb9"
      url "https://github.com/Allan-Nava/pqprobe/releases/download/v#{version}/pqprobe_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pqprobe"
  desc "Which classes of TLS client can still handshake with this endpoint"
  homepage "https://allan-nava.github.io/pqprobe/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pqprobe"

  postflight do
    if system_command "/usr/bin/xattr", args: ["-h"], print_stderr: false
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pqprobe"]
    end
  end

  # No zap stanza required
end
