# This file was generated by GoReleaser. DO NOT EDIT.
cask "pqprobe" do
  version "0.47.0"

  on_macos do
    on_arm do
      sha256 "3882c1dfc8f15879530d8a3331e8e3a076ae7fc9df695af073a7a3eb1612512f"
      url "https://github.com/Allan-Nava/pqprobe/releases/download/v#{version}/pqprobe_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1374841173c08445f71a058777618e1afddceca1446750a1e3c54007de2be268"
      url "https://github.com/Allan-Nava/pqprobe/releases/download/v#{version}/pqprobe_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7432cac672e7a779a5b7c43fc4e5929d487dfe8764c4fa4fe4ed837254d227d9"
      url "https://github.com/Allan-Nava/pqprobe/releases/download/v#{version}/pqprobe_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "46491d8e9c3ae308d8a0d77d552685f22dfa2725c7b9169109ba7c992bd47f43"
      url "https://github.com/Allan-Nava/pqprobe/releases/download/v#{version}/pqprobe_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pqprobe"
  desc "Which classes of TLS client can still handshake with this endpoint"
  homepage "https://allan-nava.github.io/pqprobe/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pqprobe"

  postflight do
    if system_command "/usr/bin/xattr", args: ["-h"], print_stderr: false
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pqprobe"]
    end
  end

  # No zap stanza required
end
