# This file was generated by GoReleaser. DO NOT EDIT.
cask "robotsmith" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "1dfe239d085ea5206dc0eb08991bcf296bd425730a5612b4b0ada5e714997f53"
      url "https://github.com/Allan-Nava/robotsmith/releases/download/v#{version}/robotsmith_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5061019eaf23b42c75504f591b5416c8957e470d168fa849b91334336410e5b0"
      url "https://github.com/Allan-Nava/robotsmith/releases/download/v#{version}/robotsmith_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3716b9a5abb0e8cad3243edb91dc50eda9b5d8c8693a589fd101850ac1333120"
      url "https://github.com/Allan-Nava/robotsmith/releases/download/v#{version}/robotsmith_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cff98b1254c6169648c0119e27ea76ac9dbd123e3a2d96a36d9ab53d164fe159"
      url "https://github.com/Allan-Nava/robotsmith/releases/download/v#{version}/robotsmith_#{version}_linux_amd64.tar.gz"
    end
  end

  name "robotsmith"
  desc "Verifies a robots.txt and advises how to write it from your real traffic"
  homepage "https://github.com/Allan-Nava/robotsmith"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "robotsmith"

  postflight do
    if system_command "/usr/bin/xattr", args: ["-h"], print_stderr: false
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/robotsmith"]
    end
  end

  # No zap stanza required
end
