# This file was generated by GoReleaser. DO NOT EDIT.
cask "robotsmith" do
  version "0.5.1"

  on_macos do
    on_arm do
      sha256 "0c32c4b5a28a38e09be05c4f503cb77d773e8cc91749831f0ae5844a89f6da3f"
      url "https://github.com/Allan-Nava/robotsmith/releases/download/v#{version}/robotsmith_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0bb97dadc340b4dd701f6b287a2befab15fababa6c1c5b5ee23188653bb4246b"
      url "https://github.com/Allan-Nava/robotsmith/releases/download/v#{version}/robotsmith_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f70c21990e11f88e35373e4880908d5ad37c70845eee9f8e9b1d4013a7c7e925"
      url "https://github.com/Allan-Nava/robotsmith/releases/download/v#{version}/robotsmith_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "096d8c72245ec15c4d017b3b7624810b8c276a769dcb4b10f925b982d23b9723"
      url "https://github.com/Allan-Nava/robotsmith/releases/download/v#{version}/robotsmith_#{version}_linux_amd64.tar.gz"
    end
  end

  name "robotsmith"
  desc "Verifies a robots.txt and advises how to write it from your real traffic"
  homepage "https://github.com/Allan-Nava/robotsmith"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "robotsmith"

  postflight do
    if system_command "/usr/bin/xattr", args: ["-h"], print_stderr: false
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/robotsmith"]
    end
  end

  # No zap stanza required
end
