# This file was generated by GoReleaser. DO NOT EDIT.
cask "segcheck" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "4cf1745152cc3c5e998a04a2fb73212877654bf8f14695568ab52b6d8623f584"
      url "https://github.com/Allan-Nava/segcheck/releases/download/v#{version}/segcheck_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "992bd06d05ac3de048624cce3768ff9803d239708a01ad41bea5b16d289209f6"
      url "https://github.com/Allan-Nava/segcheck/releases/download/v#{version}/segcheck_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3a4075683645149d0f293fc53cfd1f277f9b9d7c305bf5a7db828abc58c8d4e8"
      url "https://github.com/Allan-Nava/segcheck/releases/download/v#{version}/segcheck_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7ead1885a2b7582b587bf68f9f3a8d34a9a51058e42b5863644fc279f80f0972"
      url "https://github.com/Allan-Nava/segcheck/releases/download/v#{version}/segcheck_#{version}_linux_arm64.tar.gz"
    end
  end

  name "segcheck"
  desc "Check what HLS/DASH segments really contain, not just what the manifest says"
  homepage "https://github.com/Allan-Nava/segcheck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "segcheck"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/segcheck"]
    end
  end

  # No zap stanza required

end
