# This file was generated by GoReleaser. DO NOT EDIT.
cask "segcheck" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "31678d77bfbf612fc2b846d808309a9c8caa9b15a47d160de250cb8db4e84009"
      url "https://github.com/Allan-Nava/segcheck/releases/download/v#{version}/segcheck_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9d3639f5bdb7f18787ea5a63072b363155a1e484bd323b73c9d372e594a6d244"
      url "https://github.com/Allan-Nava/segcheck/releases/download/v#{version}/segcheck_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "839f9361f5266bc6340d40e1ffce2b53b4c25b5e82ccd4af80d56d5fa5bfadfd"
      url "https://github.com/Allan-Nava/segcheck/releases/download/v#{version}/segcheck_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e13aaf65dcf8a36a81304be2cc6b1f0a996bb999ac319e1ef395ed88d0f7617c"
      url "https://github.com/Allan-Nava/segcheck/releases/download/v#{version}/segcheck_#{version}_linux_arm64.tar.gz"
    end
  end

  name "segcheck"
  desc "Check what HLS/DASH segments really contain, not just what the manifest says"
  homepage "https://github.com/Allan-Nava/segcheck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "segcheck"

  # No zap stanza required

end
