# This file was generated by GoReleaser. DO NOT EDIT.
cask "segcheck" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "44e5b3cd94cc8b4b668ae42511c58b33d38c5591a00ccb52e69d1edab8a581e1"
      url "https://github.com/Allan-Nava/segcheck/releases/download/v#{version}/segcheck_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0e137b7cbeff022a757bad22be20134b3989ad51df10cb3acee397df1bf91ee3"
      url "https://github.com/Allan-Nava/segcheck/releases/download/v#{version}/segcheck_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3551c03dcbfa72f4ce06e0a8a0bab2a6daf3384ed9e46e26c0897435bd4ba1f6"
      url "https://github.com/Allan-Nava/segcheck/releases/download/v#{version}/segcheck_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b965971db0422346ed0a78668b2e750293b8ef79313e64d9ed2f69b8e4a248a"
      url "https://github.com/Allan-Nava/segcheck/releases/download/v#{version}/segcheck_#{version}_linux_arm64.tar.gz"
    end
  end

  name "segcheck"
  desc "Check what HLS/DASH segments really contain, not just what the manifest says"
  homepage "https://github.com/Allan-Nava/segcheck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "segcheck"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/segcheck"]
    end
  end

  # No zap stanza required

end
