#!/usr/bin/env bash
# Rigenera Casks/checkfleet-desktop.rb dalla release di checkfleet.
#
# Perché esiste (HT-4): l'app desktop (Wails) è buildata da un workflow separato
# upstream (`desktop.yml`) e allegata alla release DOPO che goreleaser l'ha
# creata, quindi GoReleaser non la conosce e non può generare il cask. Questo
# script fa la stessa cosa a mano: risolve l'asset `darwin_universal`, ne calcola
# lo sha256 e riscrive il cask. Idempotente: se nulla cambia, il file resta
# identico e il workflow non committa.
#
# Uso:
#   scripts/render-desktop-cask.sh            # ultima release
#   scripts/render-desktop-cask.sh v0.125.0   # tag specifico
#
# Richiede: gh (autenticato o GH_TOKEN), unzip, sha256sum|shasum.
set -euo pipefail

UPSTREAM_REPO="${UPSTREAM_REPO:-Allan-Nava/checkfleet}"
CASK_PATH="${CASK_PATH:-Casks/checkfleet-desktop.rb}"
APP_NAME="checkfleet.app"
BUNDLE_ID="com.wails.checkfleet"

die() { echo "error: $*" >&2; exit 1; }
# exit 2 = "non c'è niente da fare, non è un guasto": il workflow lo tratta come
# skip. Succede quando la release CLI esiste ma il build desktop (workflow
# separato upstream) non ha ancora allegato lo zip.
skip() { echo "skip: $*" >&2; exit 2; }

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

TAG="${1:-}"
if [ -z "$TAG" ]; then
  TAG="$(gh release view --repo "$UPSTREAM_REPO" --json tagName -q .tagName)"
fi
[ -n "$TAG" ] || die "impossibile risolvere il tag della release"
VERSION="${TAG#v}"

# L'asset desktop porta il TAG nel nome (`..._v0.125.0_...`), non la versione
# nuda come gli archivi del CLI: si risolve dalla release, non si indovina.
ASSET="$(gh release view "$TAG" --repo "$UPSTREAM_REPO" --json assets \
  -q '.assets[].name | select(test("^checkfleet-desktop_.*_darwin_universal\\.zip$"))' | head -1)"
[ -n "$ASSET" ] || skip "nessun asset checkfleet-desktop_*_darwin_universal.zip nella release $TAG"

# Il cask interpola `v#{version}` nell'url: se upstream cambia lo schema dei nomi
# ce ne accorgiamo qui, non con un 404 in faccia agli utenti.
EXPECTED="checkfleet-desktop_v${VERSION}_darwin_universal.zip"
[ "$ASSET" = "$EXPECTED" ] || die "schema nome asset cambiato: trovato '$ASSET', il template si aspetta '$EXPECTED'"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
gh release download "$TAG" --repo "$UPSTREAM_REPO" --pattern "$ASSET" -D "$tmp" --clobber
SHA="$(sha256_of "$tmp/$ASSET")"

# Il bundle deve stare alla radice dello zip: `app "checkfleet.app"` non cerca
# altrove.
FOUND_APP="$(unzip -Z1 "$tmp/$ASSET" | sed -n 's|^\([^/]*\.app\)/.*|\1|p' | sort -u | head -1)"
[ "$FOUND_APP" = "$APP_NAME" ] || die "atteso $APP_NAME alla radice dello zip, trovato '${FOUND_APP:-niente}'"

mkdir -p "$(dirname "$CASK_PATH")"
cat > "$CASK_PATH" <<EOF
# This file was generated by scripts/render-desktop-cask.sh. DO NOT EDIT.
cask "checkfleet-desktop" do
  version "${VERSION}"
  sha256 "${SHA}"

  url "https://github.com/Allan-Nava/checkfleet/releases/download/v#{version}/checkfleet-desktop_v#{version}_darwin_universal.zip"
  name "checkfleet Desktop"
  desc "Desktop app to run the checkfleet infrastructure checks"
  homepage "https://github.com/Allan-Nava/checkfleet"

  livecheck do
    skip "Auto-generated on release."
  end

  # Cask macOS-only (artifact app): Homebrew pretende il depends_on nudo, senza
  # vincolo di versione (il bundle dichiara LSMinimumSystemVersion 10.13, più
  # bassa del minimo che Homebrew supporta, e la forma con versione per quelle
  # release è disabilitata).
  depends_on :macos

  app "${APP_NAME}"

  # Il bundle non è firmato né notarizzato: senza togliere la quarantine
  # Gatekeeper rifiuta di aprirlo. Stesso trattamento del cask del CLI.
  postflight do
    if system_command "/usr/bin/xattr", args: ["-h"], print_stderr: false
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/${APP_NAME}"]
    end
  end

  zap trash: [
    "~/Library/Caches/${BUNDLE_ID}",
    "~/Library/Preferences/${BUNDLE_ID}.plist",
    "~/Library/Saved Application State/${BUNDLE_ID}.savedState",
    "~/Library/WebKit/${BUNDLE_ID}",
  ]
end
EOF

echo "$CASK_PATH aggiornato: version=${VERSION} sha256=${SHA}"
