#!/usr/bin/env bash
# Confronta la `version` di ogni cask generato con l'ultima release del progetto
# upstream e, se divergono, risincronizza il cask dagli asset reali.
#
# Perché esiste (HT-26): il tap si aggiorna da sé perché GoReleaser pusha qui a
# ogni tag `v*`, e `livecheck { skip }` è voluto — la versione la spinge la
# release, non un check di Homebrew. Il buco è cosa succede quando quel push
# **non parte**: i PAT fine-grained scadono per forza, e quando scadono la release
# upstream pubblica archivi e immagine e poi muore sull'ultimo passo. Risultato:
# il tap resta alla versione vecchia **in silenzio**. Nessun job era rosso, il
# cask si caricava, l'audit passava: semplicemente serviva una release che qui non
# era mai arrivata. Questo script è il detector di quel silenzio, e in `--apply`
# anche la riparazione.
#
# Uso:
#   scripts/sync-cask-versions.sh                 # --check (default): TSV, exit 0
#   scripts/sync-cask-versions.sh --apply         # riscrive i cask in drift
#   scripts/sync-cask-versions.sh --apply abrsim  # solo alcuni cask
#
# TSV: stato <TAB> cask <TAB> versione_cask <TAB> versione_upstream <TAB> messaggio
#   sync    allineato, niente da fare
#   drift   divergente (solo in --check)
#   synced  divergente e risincronizzato (solo in --apply)
#   skip    non è un cask generato da GoReleaser (lo rende un nostro script)
#   error   qualcosa non torna: il cask NON è stato toccato
#
# Exit: 0 in `--check` sempre (un drift è un'informazione, non un guasto dello
# script); in `--apply` 1 se almeno un cask è finito in `error`.
#
# Richiede: gh (autenticato o GH_TOKEN), curl, sha256sum|shasum.
set -euo pipefail

MODE=check
CASKS=()
while [ $# -gt 0 ]; do
  case "$1" in
    --check) MODE=check ;;
    --apply) MODE=apply ;;
    -h | --help)
      sed -n '2,30p' "$0"
      exit 0
      ;;
    -*) echo "sync-cask-versions: opzione sconosciuta: $1" >&2 && exit 1 ;;
    *) CASKS+=("$1") ;;
  esac
  shift
done

report() { printf '%s\t%s\t%s\t%s\t%s\n' "$1" "$2" "$3" "$4" "$5"; }

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

# Se non è stato chiesto un cask specifico, tutti quelli del tap.
if [ "${#CASKS[@]}" -eq 0 ]; then
  for f in Casks/*.rb; do CASKS+=("$(basename "$f" .rb)"); done
fi

errors=0

for token in "${CASKS[@]}"; do
  cask="Casks/${token}.rb"
  if [ ! -f "$cask" ]; then
    report error "$token" - - "$cask non esiste."
    errors=$((errors + 1))
    continue
  fi

  # Solo i cask generati da GoReleaser: quello desktop lo rende
  # render-desktop-cask.sh dalla sua release e ha già il suo workflow.
  if ! head -n 1 "$cask" | grep -q 'generated by GoReleaser'; then
    report skip "$token" - - "Non generato da GoReleaser: lo aggiorna il suo renderer."
    continue
  fi

  have="$(sed -n 's/^  version "\(.*\)"$/\1/p' "$cask" | head -1)"
  repo="$(grep -m1 -oE 'https://github\.com/[^/]+/[^/]+/releases/download/' "$cask" |
    sed -E 's#https://github\.com/([^/]+/[^/]+)/releases/download/#\1#')"
  if [ -z "$have" ] || [ -z "$repo" ]; then
    report error "$token" "${have:--}" - "Non riesco a leggere version/url dal cask."
    errors=$((errors + 1))
    continue
  fi

  # `releases/latest` e non `gh release view`: l'endpoint `latest` esclude draft e
  # **prerelease**, e goreleaser marca le prerelease con `prerelease: auto`. Una
  # rc non deve bumpare il cask.
  want="$(gh api "repos/${repo}/releases/latest" --jq '.tag_name' 2>/dev/null | sed 's/^v//' || true)"
  if [ -z "$want" ]; then
    report error "$token" "$have" - "Nessuna release stabile su ${repo} (o API non raggiungibile)."
    errors=$((errors + 1))
    continue
  fi

  if [ "$have" = "$want" ]; then
    report sync "$token" "$have" "$want" "Allineato a ${repo}."
    continue
  fi

  if [ "$MODE" = check ]; then
    report drift "$token" "$have" "$want" "Il cask è fermo a ${have}, l'ultima release di ${repo} è ${want}: il push di GoReleaser non è arrivato (token scaduto?)."
    continue
  fi

  # --- da qui: riscrittura ---
  #
  # Si toccano SOLO la riga `version` e le righe `sha256`. Gli url non cambiano
  # mai: contengono `#{version}`, quindi si reinterpolano da soli. Ogni sha256 è
  # ricalcolato scaricando l'asset vero della release nuova — mai copiato da un
  # checksums.txt e mai scritto a mano.
  # while-read e non `mapfile`: quello è bash 4+, e su macOS /bin/bash è la 3.2
  # (i runner hosted inclusi).
  sha_lines=()
  url_lines=()
  while IFS= read -r n; do sha_lines+=("$n"); done < <(grep -n '^ *sha256 "' "$cask" | cut -d: -f1)
  while IFS= read -r n; do url_lines+=("$n"); done < <(grep -n '^ *url "' "$cask" | cut -d: -f1)
  if [ "${#sha_lines[@]}" -eq 0 ] || [ "${#sha_lines[@]}" -ne "${#url_lines[@]}" ]; then
    report error "$token" "$have" "$want" "Struttura inattesa: ${#sha_lines[@]} sha256 e ${#url_lines[@]} url."
    errors=$((errors + 1))
    continue
  fi
  # Il pairing è per posizione, quindi ogni sha256 DEVE essere seguito dalla sua
  # url. Se il template di GoReleaser cambiasse ordine, meglio rifiutare che
  # scrivere lo sha sbagliato sotto l'url sbagliata.
  pair_ok=1
  for i in "${!sha_lines[@]}"; do
    [ "${url_lines[$i]}" -eq $((sha_lines[i] + 1)) ] || pair_ok=0
  done
  if [ "$pair_ok" -ne 1 ]; then
    report error "$token" "$have" "$want" "sha256 e url non sono adiacenti: template cambiato, non tocco il file."
    errors=$((errors + 1))
    continue
  fi

  tmp="$(mktemp -d)"
  # shellcheck disable=SC2064 # il path va espanso ora, non all'uscita
  trap "rm -rf '$tmp'" EXIT

  new_shas=()
  failed=""
  for line in "${url_lines[@]}"; do
    tpl="$(sed -n "${line}s/^ *url \"\(.*\)\"$/\1/p" "$cask")"
    url="${tpl//\#\{version\}/$want}"
    out="$tmp/asset.$line"
    if ! curl -fsSL --retry 3 --retry-delay 2 -o "$out" "$url"; then
      failed="$url"
      break
    fi
    new_shas+=("$(sha256_of "$out")")
  done
  if [ -n "$failed" ]; then
    report error "$token" "$have" "$want" "Asset non scaricabile per ${want}: ${failed} — release incompleta, cask non toccato."
    errors=$((errors + 1))
    rm -rf "$tmp"
    trap - EXIT
    continue
  fi

  out="$tmp/cask.rb"
  awk -v want="$want" -v shas="$(printf '%s\n' "${new_shas[@]}" | paste -sd, -)" '
    BEGIN { split(shas, sha, ","); k = 0 }
    /^  version "/ { printf "  version \"%s\"\n", want; next }
    /^ *sha256 "/  { k++; match($0, /^ */); printf "%ssha256 \"%s\"\n", substr($0, 1, RLENGTH), sha[k]; next }
    { print }
  ' "$cask" > "$out"

  # Guard finale: il diff deve toccare SOLO version e sha256. Qualunque altra
  # riga cambiata significa che awk ha fatto un danno, e allora si butta via.
  bad="$(diff "$cask" "$out" | grep -E '^[<>]' | grep -vcE '^[<>]   *(version|sha256) "' || true)"
  if [ "$bad" -ne 0 ]; then
    report error "$token" "$have" "$want" "Il diff toccherebbe ${bad} righe che non sono version/sha256: cask non toccato."
    errors=$((errors + 1))
    rm -rf "$tmp"
    trap - EXIT
    continue
  fi

  cat "$out" > "$cask"
  rm -rf "$tmp"
  trap - EXIT
  report synced "$token" "$have" "$want" "Risincronizzato da ${repo}: version ${have} → ${want}, ${#new_shas[@]} sha256 ricalcolati dagli asset."
done

if [ "$MODE" = apply ] && [ "$errors" -gt 0 ]; then
  exit 1
fi
exit 0
